"""The extraction agent: retrieve -> extract -> validate -> verify.

DESIGN NOTES WORTH DEFENDING IN AN INTERVIEW
--------------------------------------------

**One metric per call, not ten.** Extracting all metrics in a single prompt is
cheaper but conflates failures: when the model returns a wrong net income you
cannot tell whether retrieval failed or generation did, because all ten metrics
shared one retrieved context. Per-metric calls give per-metric retrieval and a
clean attribution of blame. Cost matters less than being able to debug.

**Retrieval is metric-specific.** "What was total revenue" and "what was cash
and cash equivalents" need different parts of Item 8. A single shared context
optimises for neither.

**The model never does arithmetic.** It reports the printed number and the
scale separately; Python multiplies. See schema.py.

**Schema failure triggers a repair turn, not a crash.** The model is shown its
own invalid output and the validation error. This recovers most malformed
responses at the cost of one extra call, and the repair rate is itself a
reported metric -- a model needing repairs on 40% of calls is telling you the
prompt is unclear.

**Abstention is instructed, not punished.** The prompt explicitly permits
found=false. Models that are pushed to always answer will always answer,
including when the context is empty.
"""
from __future__ import annotations

import json
import logging

from pydantic import ValidationError

from filingiq.extraction.schema import (
    METRIC_DEFINITIONS, ExtractedFigure, ExtractionResult,
)

log = logging.getLogger(__name__)

SYSTEM_PROMPT = """You extract financial figures from SEC 10-K filings.

You will be given numbered excerpts from one company's 10-K and asked for ONE \
specific figure. Respond with a single JSON object and nothing else.

CRITICAL RULES:

1. Report the number EXACTLY as printed in the filing, in `value_as_stated`.
   Do NOT multiply it out. If the page shows 391,035 you report 391035.

2. Report the scale SEPARATELY in `scale`, taken from the table heading
   (for example "(in millions)", "(in thousands)", "$ in millions").
   Use "units" only when figures are printed in full.
   Per-share amounts (EPS) are always "units".

3. Use the figure for the CURRENT fiscal year requested. 10-K statements show
   two or three years side by side; the current year is normally the FIRST
   numeric column. Check the column heading dates before choosing.

4. If the excerpts do not contain the figure, set "found": false. Do not
   estimate, infer, or calculate it from other figures. Abstaining is correct
   and expected behaviour, not a failure.

5. Cite the excerpt number you took it from in `chunk_id`, and give a short
   supporting quote of at most 15 words.

Respond with exactly this JSON shape:
{
  "found": true or false,
  "value_as_stated": number or null,
  "scale": "units" | "thousands" | "millions" | "billions" | null,
  "currency": "USD",
  "period_end": "YYYY-MM-DD" or null,
  "chunk_id": "excerpt number you used, e.g. 3" or null,
  "quote": "short supporting text" or null,
  "confidence": 0.0 to 1.0,
  "reasoning": "one sentence on how you chose this figure and column"
}"""

USER_TEMPLATE = """Company: {ticker}
Fiscal year: {fiscal_year} (period ending approximately {period_end})

Figure required: {metric_name}
Definition: {metric_definition}

Excerpts from the 10-K:
{context}

Return the JSON object for {metric_name}."""

# Line-item captions as they actually appear in filings. These are retrieval
# queries, not descriptions -- they exist to match the surrounding text.
RETRIEVAL_ANCHORS = {
    "revenue": "Total net sales revenue consolidated statements of operations",
    "net_income": "Net income consolidated statements of operations",
    "operating_income": "Operating income total operating expenses",
    "eps_diluted": "Earnings per share diluted basic weighted-average shares",
    "total_assets": "Total assets consolidated balance sheets",
    "total_liabilities": "Total liabilities consolidated balance sheets",
    "stockholders_equity": "Total shareholders equity consolidated balance sheets",
    "cash_and_equivalents": "Cash and cash equivalents consolidated balance sheets",
    "operating_cash_flow": (
        "Cash generated by operating activities consolidated statements of cash flows"),
    "rnd_expense": "Research and development expense operating expenses",
}

# ---------------------------------------------------------------------------
# METRIC GROUPING
#
# One LLM call per metric gives clean per-metric blame attribution, which was
# the right choice while diagnosing. It is also 10x the token cost: the same
# Item 8 context is retrieved and sent ten times per filing.
#
# Metrics that appear in the SAME financial statement can share one retrieval
# and one call. Grouping by statement -- not arbitrarily -- keeps the context
# relevant to every metric in the group, so accuracy should be preserved.
# Whether it actually is, is an ablation worth running: --group vs --no-group.
#
# 10 calls x ~3,300 tokens  ->  3 calls x ~3,500 tokens = ~68% fewer tokens.
# ---------------------------------------------------------------------------
METRIC_GROUPS = {
    "income_statement": ["revenue", "operating_income", "net_income",
                         "eps_diluted", "rnd_expense"],
    "balance_sheet": ["total_assets", "total_liabilities",
                      "stockholders_equity", "cash_and_equivalents"],
    "cash_flow": ["operating_cash_flow"],
}

# ---------------------------------------------------------------------------
# STATEMENT SCOPE
#
# A 10-K contains many tables that legitimately say "Total assets" and are not
# the consolidated balance sheet:
#
#   - Parent Company Only condensed statements (SEC Rule 12-04, Schedule I)
#   - reportable segment balance sheets
#   - variable interest entity (VIE) tables
#   - regulatory capital schedules
#
# On JPMorgan filings the model read Parent-Company-Only assets ($568B) instead
# of consolidated ($3.7T) on all four years. Note that this is NOT caught by
# accounting identities: parent-only statements balance, and they report the
# SAME stockholders' equity as consolidated, so assets = liabilities + equity
# holds exactly. A coherent wrong answer defeats consistency checking.
#
# The distinguishing signal is not arithmetic but LEXICAL -- the table caption
# and its surrounding text say which statement it is.
# ---------------------------------------------------------------------------
SCOPE_EXCLUSIONS = [
    "parent company only", "parent company", "condensed financial information",
    "schedule i", "reportable segment", "segment results", "by segment",
    "variable interest entit", "regulatory capital", "supplementary information",
]

SCOPE_INSTRUCTION = """
IMPORTANT -- WHICH STATEMENT TO USE:

Use ONLY the CONSOLIDATED financial statements. A 10-K contains other tables with identical row labels that are NOT the consolidated statements:

  - "Parent Company Only" / "Condensed Financial Information of the Registrant"
  - segment or business-line tables
  - variable interest entity (VIE) tables
  - regulatory capital schedules

These are much smaller than the consolidated totals and must not be used. If an excerpt is headed or introduced by any of those phrases, ignore it and look for the consolidated statement. If only a non-consolidated table is available, set "found": false rather than reporting its figure.
"""

GROUP_ANCHORS = {
    "income_statement": ("Consolidated statements of operations net sales "
                         "revenue cost of sales operating expenses net income "
                         "earnings per share"),
    "balance_sheet": ("Consolidated balance sheets total assets total "
                      "liabilities shareholders equity cash and cash "
                      "equivalents"),
    "cash_flow": ("Consolidated statements of cash flows cash generated by "
                  "operating activities"),
}

SYSTEM_PROMPT = SYSTEM_PROMPT.replace(
    "Respond with exactly this JSON shape:",
    SCOPE_INSTRUCTION + "\nRespond with exactly this JSON shape:")

BATCH_SYSTEM_PROMPT = SYSTEM_PROMPT.replace(
    "Respond with exactly this JSON shape:",
    "You will be asked for SEVERAL figures at once. Return one object per "
    "requested figure, in a JSON array under the key \"figures\". Each object "
    "has exactly this shape:",
).replace(
    '  "reasoning": "one sentence on how you chose this figure and column"\n}',
    '  "metric": "the metric key you were asked for",\n'
    '  "reasoning": "one sentence on how you chose this figure and column"\n}\n\n'
    'Wrap them as: {"figures": [ ... ]}\n'
    'Include an object for EVERY requested metric, using "found": false for '
    'any not present in the excerpts.',
)

BATCH_USER_TEMPLATE = """Company: {ticker}
Fiscal year: {fiscal_year} (period ending approximately {period_end})

Extract these figures:
{metric_list}

Excerpts from the 10-K:
{context}

Return {{"figures": [...]}} with one object per requested metric."""

REPAIR_TEMPLATE = """Your previous response was not valid.

Response: {bad}
Error: {error}

Return a corrected JSON object with exactly the required fields. \
Output only JSON."""


def deprioritise_non_consolidated(hits: list) -> list:
    """Push parent-company / segment / VIE tables to the back of the context.

    Belt and braces alongside the prompt instruction. Excerpt order matters:
    models weight earlier context more heavily, so demoting rather than
    deleting keeps the information available while making the consolidated
    statement the first thing read. Deleting outright would risk dropping a
    filing's only usable table.
    """
    def is_scoped(h) -> bool:
        text = (h.payload.get("text") or "")[:1200].lower()
        return any(p in text for p in SCOPE_EXCLUSIONS)

    primary = [h for h in hits if not is_scoped(h)]
    secondary = [h for h in hits if is_scoped(h)]
    return primary + secondary


def build_context(hits, max_chunks: int = 6, max_chars: int = 1800) -> tuple[str, dict]:
    """Render retrieved chunks as numbered excerpts.

    Numbers rather than opaque hashes: models cite '3' reliably and
    'a4f9c2...' unreliably. The mapping back to real chunk IDs is kept here so
    provenance survives.
    """
    parts, id_map = [], {}
    for i, h in enumerate(hits[:max_chunks], start=1):
        text = (h.payload.get("text") or "")[:max_chars]
        id_map[str(i)] = h.chunk_id
        parts.append(f"--- Excerpt {i} (Item {h.payload.get('item', '?')}) ---\n{text}")
    return "\n\n".join(parts), id_map


class ExtractionAgent:
    def __init__(self, retriever, router, k: int = 6, mode: str = "hybrid",
                 min_confidence: float = 0.5):
        self.retriever = retriever
        self.router = router
        self.k = k
        self.mode = mode
        self.min_confidence = min_confidence
        self.repairs = 0
        self.schema_failures = 0

    def extract_metric(self, metric: str, ticker: str, fiscal_year: int,
                       period_end: str = "") -> ExtractedFigure:
        definition = METRIC_DEFINITIONS.get(metric, metric)
        # Query with the words that appear NEXT TO the figure in the filing,
        # not the words a person would use to ask for it. "operating cash flow"
        # rarely appears in a 10-K; "Net cash generated by operating
        # activities" is the actual line-item caption. Retrieval matches text,
        # so query in the document's vocabulary.
        anchor = RETRIEVAL_ANCHORS.get(metric, definition)
        query = f"{anchor} {ticker} {fiscal_year}"

        hits = self.retriever.search(
            query, k=self.k, mode=self.mode,
            filters={"ticker": ticker, "fiscal_year": fiscal_year},
        )
        if not hits:
            return ExtractedFigure(metric=metric, found=False,
                                   reasoning="no chunks retrieved")

        context, id_map = build_context(hits)
        retrieved_ids = [h.chunk_id for h in hits]
        user = USER_TEMPLATE.format(
            ticker=ticker, fiscal_year=fiscal_year, period_end=period_end or "unknown",
            metric_name=metric.replace("_", " "), metric_definition=definition,
            context=context)

        resp = self.router.complete(SYSTEM_PROMPT, user)
        if resp.error:
            f = ExtractedFigure(metric=metric, found=False,
                                reasoning=f"llm error: {resp.error[:80]}")
            f.retrieved_chunk_ids = retrieved_ids
            return f

        fig = self._parse(resp.text, metric)
        if fig is None:
            # One repair turn: show the model its own bad output.
            self.repairs += 1
            repair = self.router.complete(
                SYSTEM_PROMPT,
                REPAIR_TEMPLATE.format(bad=resp.text[:600], error="schema validation failed"))
            fig = self._parse(repair.text, metric)
            if fig is None:
                self.schema_failures += 1
                f = ExtractedFigure(metric=metric, found=False,
                                    reasoning="schema validation failed twice")
                f.retrieved_chunk_ids = retrieved_ids
                return f

        # Map the excerpt number back to a real chunk id, so a citation is
        # traceable to a real passage rather than a number in a prompt.
        if fig.chunk_id and fig.chunk_id in id_map:
            fig.chunk_id = id_map[fig.chunk_id]
        elif fig.found and fig.chunk_id not in id_map.values():
            fig.chunk_id = hits[0].chunk_id
            fig.confidence = min(fig.confidence, 0.5)
        fig.retrieved_chunk_ids = retrieved_ids
        return fig

    def _parse(self, text: str, metric: str) -> ExtractedFigure | None:
        try:
            data = json.loads(text.strip().removeprefix("```json").removeprefix("```")
                              .removesuffix("```").strip())
            data["metric"] = metric
            if isinstance(data.get("chunk_id"), int):
                data["chunk_id"] = str(data["chunk_id"])
            return ExtractedFigure(**data)
        except (json.JSONDecodeError, ValidationError, TypeError) as exc:
            log.debug("parse failed for %s: %s", metric, exc)
            return None

    def extract_group(self, group: str, metrics: list[str], ticker: str,
                      fiscal_year: int, period_end: str = "") -> list[ExtractedFigure]:
        """Extract several same-statement metrics from one shared context."""
        hits = self.retriever.search(
            f"{GROUP_ANCHORS[group]} {ticker} {fiscal_year}",
            k=self.k, mode=self.mode,
            filters={"ticker": ticker, "fiscal_year": fiscal_year},
        )
        if not hits:
            return [ExtractedFigure(metric=m, found=False,
                                    reasoning="no chunks retrieved") for m in metrics]

        hits = deprioritise_non_consolidated(hits)
        context, id_map = build_context(hits)
        retrieved = [h.chunk_id for h in hits]
        metric_list = "\n".join(
            f"- {m}: {METRIC_DEFINITIONS.get(m, m)}" for m in metrics)

        resp = self.router.complete(
            BATCH_SYSTEM_PROMPT,
            BATCH_USER_TEMPLATE.format(
                ticker=ticker, fiscal_year=fiscal_year,
                period_end=period_end or "unknown",
                metric_list=metric_list, context=context),
            max_tokens=2500)

        if resp.error:
            return [ExtractedFigure(metric=m, found=False,
                                    reasoning=f"llm error: {resp.error[:80]}",
                                    retrieved_chunk_ids=retrieved) for m in metrics]

        figures = self._parse_batch(resp.text, metrics)
        if figures is None:
            self.repairs += 1
            repair = self.router.complete(
                BATCH_SYSTEM_PROMPT,
                REPAIR_TEMPLATE.format(bad=resp.text[:800],
                                       error="schema validation failed"),
                max_tokens=2500)
            figures = self._parse_batch(repair.text, metrics)
            if figures is None:
                self.schema_failures += 1
                return [ExtractedFigure(metric=m, found=False,
                                        reasoning="schema validation failed twice",
                                        retrieved_chunk_ids=retrieved)
                        for m in metrics]

        for f in figures:
            if f.chunk_id and f.chunk_id in id_map:
                f.chunk_id = id_map[f.chunk_id]
            elif f.found and f.chunk_id not in id_map.values():
                f.chunk_id = hits[0].chunk_id
                f.confidence = min(f.confidence, 0.5)
            f.retrieved_chunk_ids = retrieved
        return figures

    def _parse_batch(self, text: str, metrics: list[str]) -> list[ExtractedFigure] | None:
        try:
            raw = text.strip().removeprefix("```json").removeprefix("```")
            data = json.loads(raw.removesuffix("```").strip())
            items = data.get("figures", data if isinstance(data, list) else [])
            got: dict[str, ExtractedFigure] = {}
            for d in items:
                if not isinstance(d, dict) or "metric" not in d:
                    continue
                if isinstance(d.get("chunk_id"), int):
                    d["chunk_id"] = str(d["chunk_id"])
                try:
                    fig = ExtractedFigure(**d)
                    got[fig.metric] = fig
                except ValidationError:
                    continue
            if not got:
                return None
            # A metric the model silently omitted is an abstention, not a
            # missing row -- never let a dropped metric vanish from the count.
            return [got.get(m, ExtractedFigure(metric=m, found=False,
                                               reasoning="omitted by model"))
                    for m in metrics]
        except (json.JSONDecodeError, TypeError, AttributeError):
            return None

    def extract_filing(self, ticker: str, fiscal_year: int, accession: str,
                       metrics: list[str], period_end: str = "",
                       grouped: bool = True) -> ExtractionResult:
        before = self.router.usage.summary()
        if grouped:
            figures = []
            for group, group_metrics in METRIC_GROUPS.items():
                wanted = [m for m in group_metrics if m in metrics]
                if wanted:
                    figures += self.extract_group(group, wanted, ticker,
                                                  fiscal_year, period_end)
            covered = {f.metric for f in figures}
            for m in metrics:
                if m not in covered:
                    figures.append(self.extract_metric(m, ticker, fiscal_year,
                                                       period_end))
        else:
            figures = [self.extract_metric(m, ticker, fiscal_year, period_end)
                       for m in metrics]
        after = self.router.usage.summary()
        return ExtractionResult(
            accession=accession, ticker=ticker, fiscal_year=fiscal_year,
            figures=figures, model=self.router.model,
            tokens_in=after["tokens_in"] - before["tokens_in"],
            tokens_out=after["tokens_out"] - before["tokens_out"],
            cost_usd=round(after["cost_usd"] - before["cost_usd"], 5),
        )
